spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    #url: jdbc:mysql://127.0.0.1:3306/spring_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: Christal
    password: 123456
env:
  dev999000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
girl:
  name: 668800GitHub
  age: 6688
